<script>
	import DottedArrowDown from '../components/icons/DottedArrowDown.svelte';
	import FeatureCard from "../components/ui/FeatureCard.svelte";
	import {Button} from "bits-ui";

	const HEADING = "Network Anomaly Detection"
</script>

<main class="container pt-8">
	<div class="flex h-[90vh] flex-col items-center justify-center">
		<h1 class="text-4xl flex font-semibold text-text-primary">
			{#each HEADING as letter}
				{#if letter === ' '}
					<div class="w-5"></div>
				{:else}
					<span class="inline-block hover:-translate-y-1 transition-all">{letter}</span>
				{/if}
			{/each}
		</h1>
		<p class="max-w-[40rem] text-center text-wrap text-text-secondary">
			Upload your network traffic logs and instantly detect unusual behavior, suspicious activity, potential cyber threats and view insights.
		</p>
		<div class="mt-6 flex justify-center items-center gap-6">
			<Button.Root class="rounded bg-text-primary px-4 py-2 font-semibold text-primary active:transition-all active:scale-[0.98]" href="upload">Upload CSV To Analyze</Button.Root>
			<Button.Root class="rounded border-dashed px-4 py-2 text-text-primary border border-border-primary active:transition-all active:scale-[0.98]" href="#how-it-works">How It Works</Button.Root>
		</div>

<!--		<div class="absolute bottom-44 flex flex-col items-center">-->
<!--			<p class="text-sm font-medium text-text-secondary">Scroll to view more</p>-->
<!--			<DottedArrowDown class="mt-2 h-[2rem] w-[2rem] animate-bounce text-text-secondary" />-->
<!--		</div>-->
	</div>
	<section id="features" class="flex flex-col items-center space-y-4 mb-56">
		<h2 class="text-3xl font-semibold text-text-primary">Features</h2>
		<div class="grid grid-cols-3 gap-5">
			<FeatureCard title="Feature 1" desc="Anomaly detection for cybersecurity & network monitoring" />
			<FeatureCard title="Feature 2" desc="Supports CSV network traffic exports" />
			<FeatureCard title="Feature 3" desc="Visual breakdowns & summary statistics" />
		</div>
	</section>

	<section id="how-it-works" class="flex flex-col items-center space-y-4 mb-56">
		<h2 class="text-3xl font-semibold text-text-primary">How It Works</h2>
		<div class="grid grid-cols-3 gap-5">
			<FeatureCard title="1. Upload Network Data" desc="Upload a CSV of traffic data that follows __this__ format" />
			<FeatureCard title="2. AI Detection Engine" desc="Our model analyzes network activity patterns and flags anomalies in real-time." />
			<FeatureCard title="3. Clear Output Insights" desc="Receive structured results, including anomaly scores, flagged records, and detection insights." />
		</div>
	</section>


	<section class="flex flex-col items-center space-y-4 mb-56">
		<h2 class="text-3xl font-semibold text-text-primary">The Datasets</h2>
		<p class="max-w-[62rem] text-text-secondary text-center">Our anomaly detection engine is trained and validated using industry-accepted intrusion detection datasets to ensure high accuracy and modern threat coverage.</p>
		<div class="grid grid-cols-2">

			<div class="flex items-center">
				<div class="rounded-lg border border-dashed border-border-primary bg-primary px-4 py-3 max-w-96 h-full">
					<h3 class="text-text-primary text-lg font-semibold text-center">CIC-IDS-2017</h3>
					<p class="text-text-secondary text-center">developed by the Canadian Institute for Cybersecurity</p>
					<p class="text-text-primary mt-8 text-center">Focuses:</p>
					<ul class="text-text-secondary text-sm text-center">
						{#each ["DDoS & DoS attacks", "Brute-force attempts", "Botnets", "Infiltration traffic", "Malicious access patterns"] as item}
							<li class="p-2 rounded">{item}</li>
						{/each}
					</ul>
				</div>

				<div class="h-[4px] bg-border-primary w-[32px]"></div>
			</div>
			<div class="rounded-lg border border-dashed border-border-primary bg-primary px-4 py-3 max-w-96">
				<h3 class="text-text-primary text-lg font-semibold text-center">UNSW-NB15</h3>
				<p class="text-text-secondary text-center">Generated by the Cyber Range Lab at UNSW Canberra</p>
				<p class="text-text-primary mt-8 text-center">Focuses:</p>
				<ul class="text-text-secondary text-sm text-center">
					{#each ["Hybrid normal/attack traffic", "Realistic modern attack vectors", "Deep packet", "Flow-based features", "Reconnaissance & shellcode"] as item}
						<li class="p-2 rounded">{item}</li>
					{/each}
				</ul>
			</div>		</div>
	</section>
</main>
